version: "2.1"
services:
  app:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      -  npm
      -  start
    volumes:
      - .:/home/node/spotify-radio
      - node_modules:/home/node/spotify-radio/node_modules
    ports:
      - 3000:3000
  test:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      - .:/home/node/spotify-radio
      - node_modules:/home/node/spotify-radio/node_modules
  test-watch:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/home/node/spotify-radio
      - node_modules:/home/node/spotify-radio/node_modules
  test-coverage:
    image: spotify-radio
    build: .
    user: node
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/home/node/spotify-radio
      - node_modules:/home/node/spotify-radio/node_modules

volumes:
  node_modules: {}